18 | new transaction button
BUI-studies/kurkulyator pull request #20
Opened 2023-10-08 09:28 UTC by AKot1988

resolves https://github.com/BUI-studies/kurkulyator/issues/18

2023-10-09 11:40 UTC, AKot1988 commented
Hello Nick.
I've finished transactionForm component and dont know does my last pullrequest consist this changes. Can you check this pls

If pullrequest doesnt consit changes : should i have to create new one pullRequest

2023-10-09 20:33 UTC, AKot1988 commented
Add to new Form component modal window method

2023-10-18 07:26 UTC, BUI-studies requested changes

2023-10-18 07:26 UTC, BUI-studies commented on src/components/ModalWindow/ModalWindow.js
> +};
add close() method, that would allow to hide modal window outside of the component.

2023-10-18 07:26 UTC, BUI-studies commented on src/components/TransactionForm/TransactionForm.js
> +    form: document.createElement('form'),
you're not required to place word `form` into each and every property name

2023-10-18 07:26 UTC, BUI-studies commented on src/components/TransactionForm/TransactionForm.js
> +    formType: document.createElement('select'),
this field should change the way wallet's inputs are shown.

type `income` - should show only `to` wallet
type `outcome` - only `from` wallet
type `transaction` - should show both
type `correction` - should also show only `to` wallet

2023-10-18 07:27 UTC, BUI-studies commented on src/components/TransactionForm/TransactionForm.js
> +
after you added a transaction to the collection you should get each wallet that it has and change it's balance

2023-11-08 10:06 UTC, BUI-studies approved these changes
LGTM for now

2023-11-08 10:07 UTC, merged