Category page
BUI-studies/kurkulyator pull request #40
Opened 2023-11-26 10:14 UTC by AKot1988

2023-11-26 22:11 UTC, AKot1988 commented
last commit includes method which create new category and add it to firebase collection categoriesCollectionRef

2023-11-29 08:23 UTC, ohiienko-r requested changes

2023-11-29 08:23 UTC, ohiienko-r commented on src/pages/Cetegories/Categories.js
> +  this.addButton.onclick = (e) => this.handleNewCategoryClick(e);
Так в тебе ж вже при створенні батону передається онклік івент, нашо воно ще раз тут?

2023-11-29 08:23 UTC, ohiienko-r commented on src/components/CategoryForm/CategoryForm.js
> +import { categoriesCollectionRef } from '../../../firebase';
В нас же аліаси для шляхів, ну

2023-11-29 08:23 UTC, ohiienko-r commented on src/components/CategoryForm/CategoryForm.js
> +    console.log('Category already exists');
Нада видалять консоль логи

2023-11-29 08:28 UTC, AKot1988 commented on src/components/CategoryForm/CategoryForm.js
> +    console.log('Category already exists');
done, all 'console.log'  is cleaned up!

2023-11-29 08:29 UTC, AKot1988 commented on src/pages/Cetegories/Categories.js
> +  this.addButton.onclick = (e) => this.handleNewCategoryClick(e);
agree! this row isn't nesesary

2023-12-03 08:35 UTC, BUI-studies requested changes
few minor comments and it's good to go

2023-12-03 08:35 UTC, BUI-studies commented on src/pages/Cetegories/Categories.js
> +    afterSubmit: () => modalForm.close(),
also rerender the page to show renewed list of categories

2023-12-03 08:35 UTC, BUI-studies commented on src/components/CategoryForm/CategoryForm.js
> +      options: Object.values(TRANSACTION_TYPE), // ['income', 'outcome', ...]
change it to show only 2 transaction types, because it's not a good thing to give user ability to create categories with type `transfer` or `correction`

2023-12-03 08:35 UTC, BUI-studies commented on src/components/CategoryForm/CategoryForm.js
> +    addNewCategory(categoriesCollectionRef, newCategoryToAdd);
```suggestion
    await addNewCategory(categoriesCollectionRef, newCategoryToAdd);
```

2023-12-03 08:35 UTC, BUI-studies commented on src/pages/Cetegories/Categories.js
> +  // this.addButton.onclick = (e) => this.handleNewCategoryClick(e);
if you leave the comment, you should remove it before asking for review

2023-12-03 09:18 UTC, AKot1988 commented on src/components/CategoryForm/CategoryForm.js
> +      options: Object.values(TRANSACTION_TYPE), // ['income', 'outcome', ...]
Solve by creting new object without extra values

2023-12-03 09:43 UTC, AKot1988 commented on src/pages/Cetegories/Categories.js
> +    afterSubmit: () => modalForm.close(),
I've added Router.navigate(ROUTES_NAMES.CATEGORIES) after submit/create new category

2023-12-03 09:59 UTC, BUI-studies approved these changes
i trust you more than myself

2023-12-03 10:01 UTC, ohiienko-r approved these changes
LGTM

2023-12-03 10:02 UTC, merged